language: c

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      compiler: clang
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: precise
      compiler: clang
    - os: linux
      dist: precise
      compiler: gcc

sudo: required

before_install:
  - sudo apt-get update --quiet --assume-yes
  - sudo apt-get install splint --quiet --assume-yes
  - sudo apt-get install valgrind --quiet --assume-yes

before_script:
  - mkdir .deps
  - git clone --depth=1 https://bugs.otr.im/lib/libotr.git .deps/libotr
  - pushd .deps/libotr && ./bootstrap && ./configure --prefix=$PREFIX && make && make install && popd
  # Dependencies for libotr-ng
  - curl https://www.gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.26.tar.bz2 | tar xjf - -C .deps
  - pushd .deps/libgpg-error-1.26 && ./configure --prefix=$PREFIX && make && make install && popd
  - curl https://www.gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.8.1.tar.bz2 | tar xjf - -C .deps
  - pushd .deps/libgcrypt-1.8.1 && ./configure && make && make install && popd
  - git clone -b stable --depth=1 https://github.com/jedisct1/libsodium.git .deps/libsodium &&
  - pushd .deps/libsodium && ./autogen.sh && ./configure && make && sudo make install && popd;
  - git clone --depth=1 https://github.com/otrv4/libgoldilocks .deps/libgoldilocks
  - pushd .deps/libgoldilocks && ./autogen.sh && ./configure && make && sudo make install && popd
  - git clone --depth=1 https://github.com/otrv4/libotr-ng.git .deps/libotr-ng
  - pushd .deps/libotr-ng && ./autogen.sh && ./configure && make && sudo make install && popd

script:
  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
  - ./autogen.sh && ./configure
  - if [[ $(lsb_release -c -s) == "precise" ]]; then make test; fi
  - if [[ $(lsb_release -c -s) == "trusty" ]];  then make ci;   fi
