language: c

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      compiler: clang
      env: TYPE=build
    - os: linux
      dist: trusty
      compiler: gcc
      env: TYPE=build
    - os: linux
      dist: precise
      compiler: clang
      env: TYPE=build
    - os: linux
      dist: precise
      compiler: gcc
      env: TYPE=build
    - os: linux
      dist: trusty
      compiler: clang
      env: TYPE=lint

sudo: required

before_install:
  - if [[ "$TYPE" = "build" ]]; then
        sudo apt-get update --quiet --assume-yes;
        sudo apt-get install splint --quiet --assume-yes;
        sudo apt-get install valgrind --quiet --assume-yes;
    fi
  - if [[ "$TYPE" = "lint" ]]; then
        sudo apt-get install clang-format-3.9 --quiet --assume-yes;
    fi

before_script:
  - mkdir .deps
  - curl https://www.gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.26.tar.bz2 | tar xjf - -C .deps
  - pushd .deps/libgpg-error-1.26 && ./configure && make && sudo make install && popd
  - curl https://www.gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.8.1.tar.bz2 | tar xjf - -C .deps
  - pushd .deps/libgcrypt-1.8.1 && ./configure && make && sudo make install && popd
  - git clone --depth=1 https://bugs.otr.im/lib/libotr.git .deps/libotr
  - pushd .deps/libotr && ./bootstrap && ./configure && make && sudo make install && popd
  # Dependencies for libotr-ng
  - curl https://download.libsodium.org/libsodium/releases/old/libsodium-1.0.11.tar.gz | tar xzf - -C .deps
  - pushd .deps/libsodium-1.0.11 && ./autogen.sh && ./configure && make && sudo make install && popd
  - git clone --depth=1 https://github.com/otrv4/libgoldilocks .deps/libgoldilocks
  - pushd .deps/libgoldilocks && ./autogen.sh && ./configure && make && sudo make install && popd
  - git clone --depth=1 https://github.com/otrv4/libotr-ng.git .deps/libotr-ng
  - pushd .deps/libotr-ng && ./autogen.sh && ./configure && make && sudo make install && popd

script:
  - if [[ "$TYPE" = "build" ]]; then
        export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH;
        ./autogen.sh;
        ./configure;
        make;
        make test;
        sudo make install;
    fi
  - if [[ "$TYPE" = "lint" ]]; then
        make code-style-check;
    fi
